### PR TITLE
Disabling/improving RailsFind in javascript files?

### PR DESCRIPTION
**Pull request by jdelStrother**
Hi there - I'm struggling with RailsFind in javascript files.

If have a vimrc that just loads vim-rails, and tweaks suffixes for javascript files : 

```vim
set nocompatible
filetype off " force reloading of filetype
set rtp+=~/.vim/bundle/vundle/
call vundle#begin()
Bundle 'tpope/vim-rails'
call vundle#end()

autocmd FileType javascript set suffixesadd=.js
```

and I try to use `gf` on this : 

```js
require('utilities/images')
```

then vim warns me `E345: Can't find file "utilities/images.rb" in path`.

If I disable vim-rails, or map RailsFind to something else, then it successfully opens `utilities/images.js`.

Any suggestions on either disabling RailsFind in my javascript, or making it smarter about opening my javascript modules?

### CODE REVIEW

**Comment by jdelStrother** [comment]
How's this?

**Comment by tpope** [comment]
I think the find `s:findfromview` stuff should be moved down below the early bail because it's not relevant to the asset types. Probably not a problem in practice but would rather get this right while we're at it.

**Comment by jdelStrother** [comment]
True.  I'll take another stab at it later.

**Comment by jdelStrother** [comment]
OK, updated.

**Comment by tpope** [comment]
Thanks!

**Pull request merged**
