### PR TITLE
Highlight "given" in specs

### PR DESCRIPTION
**Pull request by glittershark**
https://github.com/jnicklas/capybara#using-capybara-with-rspec

### CODE REVIEW

**Comment by tpope** [comment]
RSpec highlighting already should be a separate plugin. I don't want to go down the road of supporting Capybara as well.

This would also be pretty easy to do with `"keywords"` in `g:rails_gem_projections['capybara']`.

**Comment by glittershark** [comment]
You're already highlighting `feature`,  `background`,  and `scenario`, which are all part of the same DSL.

**Comment by glittershark** [comment]
Definitely on board with rspec highlighting going in a plugin, though.

**Comment by tpope** [comment]
ehhhhh okay fine

**Pull request merged**
