### PR TITLE
Add syntax highlighting/abbrev for assert_includes

### PR DESCRIPTION
**Pull request by lorenzk**
http://ruby-doc.org/stdlib-1.9.2/libdoc/minitest/unit/rdoc/MiniTest/Assertions.html#method-i-assert_includes

### CODE REVIEW

**Comment by tpope** [comment]
Syntax highlighting is great. I really wanna get out of the abbrev business so please drop that.

**Comment by lorenzk** [comment]
Dropped it. Some anecdata: I never used abbreviations and never paired with anyone who did, so you're probably right about that :-) Thanks for making all these awesome vim plugins btw! I use 6 of yours.

**Comment by tpope** [comment]
Can you fix the commit message? Thanks

**Comment by lorenzk** [comment]
Sorry, done.

**Pull request merged**
