### PR TITLE
Highlight `assert_not_includes`

### PR DESCRIPTION
**Pull request by axxiax**

### CODE REVIEW

**Comment by tpope** [comment]
Are the `assert_not` matchers still a thing? I thought `refute` largely superseded them.

**Comment by kassiansun** [comment]
@tpope According to http://guides.rubyonrails.org/testing.html, Rails 5.0 doesn't have refute methods anymore.

**Comment by tpope** [comment]
To be clear, that page favors `assert_not`, but the `refute` assertions are definitely still a standard part of Minitest. No amount of (outdated?) Rails documentation will change that.

**Comment by kassiansun** [comment]
@tpope Should we split `minitest` assertions from `rails` assertions? It's hard to track upstream `rails` updates with such a long list.

**Comment by tpope** [comment]
That sounds like a good idea.

**Pull request merged**
