### PR TITLE
Highlight `concering` everywhere

### PR DESCRIPTION
**Pull request by glittershark**
http://api.rubyonrails.org/v4.1.5/classes/Module/Concerning.html

### CODE REVIEW

**Comment by tpope** [comment]
Your link is incorrect. My recollection is that `with_options` is very old and I don't think I've ever seen anyone actually use it, leading me to the impression it's more of an implementation detail.

**Comment by glittershark** [comment]
I use it all the time for passing `:if` procs to a group of validations, which iirc is the primary use case.

**Comment by tpope** [comment]
I guess not much harm in highlighting it regardless. I'm just generally loathe to highlight anything globally.

And goes without saying but your link wasn't incorrect, I just confused myself and posted on the wrong issue.

**Comment by glittershark** [comment]
no worries :smile:

**Pull request merged**
