### PR TITLE
Add missing Minitests assertions

### PR DESCRIPTION
**Pull request by workgena**
As a references were used following resources:

* http://docs.seattlerb.org/minitest/Minitest/Assertions.html
* https://ruby-doc.org/stdlib-2.1.1/libdoc/test/unit/rdoc/Test/Unit/Assertions.html
* https://edgeguides.rubyonrails.org/testing.html
  - 2.4 Available Assertions

New assertions:

```ruby
assert_empty
assert_in_epsilon
assert_mock
assert_not_empty
assert_not_in_delta
assert_not_in_epsilon
assert_not_instance_of
assert_not_kind_of
assert_not_operator
assert_not_predicate
assert_not_respond_to
assert_not_send
assert_output
assert_predicate
assert_raises
assert_raise_with_message
assert_silent
```

### CODE REVIEW

**Comment by workgena** [comment]
The following assertions are missed as well:

```ruby
assert_not_in_delta
assert_in_epsilon
assert_not_in_epsilon
assert_raises
assert_not_instance_of
assert_not_kind_of
assert_not_respond_to
assert_not_operator
assert_predicate
assert_not_predicate
```

Can add them too. What about adding them on a separate line?

```vim
syn keyword rubyAssertion assert_not_in_delta assert_in_epsilon assert_not_in_epsilon assert_raises assert_not_instance_of assert_not_kind_of assert_not_respond_to assert_not_operator assert_predicate assert_not_predicate
```

**Comment by tpope** [comment]
Not sure how I missed all these. I think we should have one line for the minitest built-ins, which should be more or less identical to the `refute` line, and one line for the Rails extensions.

**Comment by tpope** [comment]
Actually, we'd need an additional line for `assert` vs `assert_not` built-ins, I think.

**Comment by workgena** [comment]
Ok, I've removed previous commit. And add the following blocks:

line_1: refute_*
line_2: assert_*
line_3: assert_not_*

line_4: assert_*
line_5: assert_not_*

" assertions without equivalents/opposits
line_6: assert_*

As a references were used following resources:

* http://docs.seattlerb.org/minitest/Minitest/Assertions.html
* https://ruby-doc.org/stdlib-2.1.1/libdoc/test/unit/rdoc/Test/Unit/Assertions.html
* https://edgeguides.rubyonrails.org/testing.html
  - 2.4 Available Assertions

**Comment by tpope** [comment]
Looks great, thanks.

**Pull request merged**
